name       : fcgi
version    : 2.4.2
release    : 4
source     :
    - https://github.com/FastCGI-Archives/fcgi2/archive/2.4.2.tar.gz : 1fe83501edfc3a7ec96bb1e69db3fd5ea1730135bd73ab152186fd0b437013bc
license    : OML
component  : programming.library
summary    : FASTCgi (fcgi) is a language independent, high performant extension to CGI
description: |
    FASTCgi (fcgi) is a language independent, high performant extension to CGI
setup      : |
    sed -i 's/\r//' doc/fastcgi-prog-guide/ch2c.htm
    chmod a-x include/fcgios.h libfcgi/os_unix.c
    %autogen --disable-static
build      : |
    unset LD_AS_NEEDED
    %make -j1
install    : |
    unset LD_AS_NEEDED
    %make_install
