name       : fcgi
version    : 2.4.0
release    : 1
source     :
    - https://solus-project.com/sources/fcgi-2.4.0.tar.gz : 66fc45c6b36a21bf2fbbb68e90f780cc21a9da1fffbae75e76d2b4402d3f05b9
license    : OML
component  : programming
summary    : FASTCgi (fcgi) is a language independent, high performant extension to CGI
description: |
    FASTCgi (fcgi) is a language independent, high performant extension to CGI
setup      : |
    %apply_patches
    sed -i 's/\r//' doc/fastcgi-prog-guide/ch2c.htm
    chmod a-x include/fcgios.h libfcgi/os_unix.c
    %reconfigure --disable-static
build      : |
    unset LD_AS_NEEDED
    %make -j1
install    : |
    unset LD_AS_NEEDED
    %make_install
