name       : fcgi
version    : 2.4.0
release    : 1
source     :
    - https://solus-project.com/sources/fcgi-2.4.0.tar.gz : 66fc45c6b36a21bf2fbbb68e90f780cc21a9da1fffbae75e76d2b4402d3f05b9
license    : OML
component  : programming
summary    : FASTCgi (fcgi) is a language independent, high performant extension to CGI
description: |
    FASTCgi (fcgi) is a language independent, high performant extension to CGI
setup      : |
    %patch -p1 < $pkgfiles/fcgi-2.4.0-configure.in.patch
    %configure --disable-static
build      : |
    %make
install    : |
    %make_install
